// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1fKvnYYA4eSKmbZj1hCSwRrYmXWBfDf8',
    appId: '1:198443042075:web:dac611ddc08272ae99ffbe',
    messagingSenderId: '198443042075',
    projectId: 'social-app-caa25',
    authDomain: 'social-app-caa25.firebaseapp.com',
    storageBucket: 'social-app-caa25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAsYogFz4VpqYcDwScO9CdL9IFqQaNjw',
    appId: '1:198443042075:android:1539848d6645ed3d99ffbe',
    messagingSenderId: '198443042075',
    projectId: 'social-app-caa25',
    storageBucket: 'social-app-caa25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsM8mk4T8ykeG6stffsXcFwWL-z19unv0',
    appId: '1:198443042075:ios:2ac2e045a43dcbb499ffbe',
    messagingSenderId: '198443042075',
    projectId: 'social-app-caa25',
    storageBucket: 'social-app-caa25.appspot.com',
    iosClientId: '198443042075-tbv2i5i8shdi8pgbr3ot9ukpp3vsbrem.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
